Merge implementing api
SayNya/async_parser pull request #2
Opened 2022-02-10 14:33 UTC by SayNya

Не удалось заджоинить связь many-to-many (weather_repository)

2022-02-11 06:58 UTC, Alexundar requested changes

2022-02-11 06:58 UTC, Alexundar commented on .gitignore
> +#   However, in case of collaboration, if having platform-specific dependencies orm dependencies
почему orm вместо or

2022-02-11 06:58 UTC, Alexundar commented on src/api/views/weather/weather_view.py
> +async def read_weather(parameters_schema: WeatherParameters = Depends(),
давай к роутам добавлять еще минимальную документацию
https://fastapi.tiangolo.com/tutorial/metadata/#metadata-for-api
https://fastapi.tiangolo.com/advanced/path-operation-advanced-configuration/#openapi-extra

2022-02-11 06:58 UTC, Alexundar commented on src/api/views/weather/weather_view.py
> +    response.headers['Content-Disposition'] = 'attachment; filename=export.csv'
формирование SreamingResponse вынести в get_weather_csv

2022-02-11 06:58 UTC, Alexundar commented on src/orm/alembic/versions/63ca63ba35b6_a.py
> +    pass
пустые миграции лучше не комитить

2022-02-11 06:58 UTC, Alexundar commented on src/orm/async_database.py
> +    async def create_database(self) -> None:
я думаю, что эти три метода нам тут не нужны будут

2022-02-11 06:58 UTC, Alexundar commented on src/orm/async_database.py
> +async_database = AsyncDatabase(settings.database_uri)
давай попробуем организовать взаимодействие fast api и бд через dependency injection https://python-dependency-injector.ets-labs.org/examples/fastapi-sqlalchemy.html

2022-02-11 06:58 UTC, Alexundar commented on src/orm/models/weather/weather_condition.py
> +    weather_id = Column(Integer(), ForeignKey('weather.id'), primary_key=True)
можно просто Integer передавать, не вызывая

2022-02-11 06:58 UTC, Alexundar commented on src/orm/repositories/__init__.py
> +weather_condition_repository = WeatherConditionRepository(async_database.session)
используя dependency injection сущности репозиториев будут создаваться в контейнере

2022-02-11 06:58 UTC, Alexundar commented on src/orm/repositories/base_repository.py
> +    async def create(self, model) -> None:
не забываем про type hints для session_factory и model

2022-02-11 06:58 UTC, Alexundar commented on src/orm/repositories/base_repository.py
> +    async def find_by(self, **parameters: dict):
и тут тоже нужно добавить, что эта функция возвращает

2022-02-11 06:58 UTC, Alexundar commented on src/orm/repositories/weather/weather_repository.py
> +    async def find_between(self, **kwargs):
тут все же лучше передавать не **kwargs, а явно start_date и end_date, так как суть функции find_between искать конкретно между датами + кроме этих параметров тут из kwargs ничего не используется + не забываем про type hints

2022-02-11 06:58 UTC, Alexundar commented on src/orm/repositories/weather/weather_repository.py
> +    async def find_all(self):
type hints

2022-02-11 06:58 UTC, Alexundar commented on src/orm/repositories/weather/weather_repository.py
> +                join(DayTime). \
без join selectinload не сработает?

2022-02-11 06:58 UTC, Alexundar commented on src/services/weather/weather_service.py
> +    @staticmethod
если будем использовать подход dependecy injection, то добавим init метод в котором будем получать сущность репозитория 
```
def __init__(self, weather_repository: WeatherRepository) -> None:
        self.weather_repository: WeatherRepository = weather_repository
```
тогда методы этого сервиса не будут static

2022-02-11 06:58 UTC, Alexundar commented on src/services/base_service.py
> +class BaseService:
давай пока что уберем BaseService

2022-02-11 06:58 UTC, Alexundar commented on src/services/weather/weather_service.py
> +    async def save_weather(weather_list: List[dict]):
type hint для возвращаемого значения

2022-02-11 06:58 UTC, Alexundar commented on src/services/weather/weather_service.py
> +        if query.dict()['start_date']:
query.start_date

2022-02-11 06:58 UTC, Alexundar commented on src/services/weather/weather_service.py
> +        stream = io.StringIO()
вынести логику по csv в CSVService

2022-02-11 06:58 UTC, Alexundar commented on src/services/weather/weather_service.py
> +def model_to_csv_line(model: WeatherResponse):
тоже в CSVService

2022-02-11 06:58 UTC, Alexundar commented on src/weather_collector/crawler/weather_crawler.py
> +        self.HEAD_URL = os.environ.get('HEAD_URL')
все-таки давай тут тоже через setting возьмем

2022-02-11 06:58 UTC, Alexundar commented on src/weather_collector/crawler/weather_crawler.py
> +        dates = self.get_dates(start_date=get_previous_date())
переименуй функцию в crawl_content_for_previous_day и отправь запрос просто для вчерашней даты, не формируя массив

2022-02-11 06:58 UTC, Alexundar commented on src/weather_collector/http_client/async_client.py
> +    async def get_html(self, url):
пусть будет просто метод get

2022-02-11 06:58 UTC, Alexundar commented on src/weather_collector/http_client/abstract_client.py
> +    def __aexit__(self, exc_type, exc_val, exc_tb):
если запрос упадет с ошибкой, делаем raise с данными об ошибке
```
async def __aexit__(self, exception_type, exception_value, exception_traceback):
        if exception_value:
            raise
```

2022-02-11 06:58 UTC, Alexundar commented on src/weather_collector/http_client/abstract_client.py
> +    def get_html(self, url):
async def

2022-02-11 06:58 UTC, Alexundar commented on src/weather_collector/http_client/abstract_client.py
> +    def __aenter__(self):
async def

2022-02-11 06:58 UTC, Alexundar commented on src/weather_collector/http_client/async_client.py
> +        await self.session.close()
если запрос упадет с ошибкой, пробросим на верх данные об ошибке
```
async def __aexit__(self, exception_type, exception_value, exception_traceback):
        await super().__aexit__(exception_type, exception_value, exception_traceback)
        await self.session.close()
```

2022-02-11 06:58 UTC, Alexundar commented on src/weather_collector/main.py
> +    # await writer.save_content(result)
убираем комменты

2022-02-11 06:58 UTC, Alexundar commented on src/weather_collector/parser/weather_parser.py
> +        dte = datetime.strptime(dte, '%Y-%m-%d').date()
переименуй в current_date

2022-02-11 06:58 UTC, Alexundar commented on src/weather_collector/parser/weather_parser.py
> +        times = bs.find_all('tr', class_='time')
day_times

2022-02-11 06:58 UTC, Alexundar commented on src/weather_collector/parser/weather_parser.py
> +        for tm in times:
for day_time in day_times

2022-02-11 06:58 UTC, Alexundar commented on src/weather_collector/parser/weather_parser.py
> +                x.strip() for x in tm.find('td', class_='temp').get_text().split('\n') if not x.isspace())
`temperature = [x.strip() for x in tm.find('td', class_='temp').get_text().split('\n') if not x.isspace())]`

2022-02-11 06:58 UTC, Alexundar commented on src/weather_collector/parser/weather_parser.py
> +            condition = list(map(str.strip, tm.find('td', class_='icon').get_text().strip().split(',')))
тут тоже можно через list comprehension

2022-02-11 06:58 UTC, Alexundar commented on src/weather_collector/utils/utlis.py
> +    return (datetime.today() - timedelta(days=1)).date()
сюда можно добавить метод для получение текущей даты + переименуй файл в date_utils

2022-02-11 06:58 UTC, Alexundar commented on .env.example
> +DATABASE_URI=
здесь все-таки лучше еще этим переменным присвоить значения для примера

2022-02-12 17:31 UTC, Alexundar requested changes

2022-02-12 17:31 UTC, Alexundar commented on src/orm/repositories/weather/weather_repository.py
> +            print('1' * 100)
убрать print

2022-02-12 17:31 UTC, Alexundar commented on src/orm/repositories/weather/weather_repository.py
> +            query = select(Weather, WindDirection.direction). \
давай попробуем так
```
query = select(Weather, WindDirection.direction, плюс другие поля заджойненых таблиц). \
                join(Weather.day_time). \
                join(Weather.wind_direction). \
                join(Weather.conditions)
```

2022-02-12 17:31 UTC, Alexundar commented on src/services/csv/csv_service.py
> +    def convert_weather_to_csv_response(self, data_list: list) -> StreamingResponse:
давай попробуем этот метод сделать более гибким, чтобы можно было сформировать StreamingResponse для csv любой структуры.
будем передавать сюда заголовки, массив данных и шаблон, по которому данные будут формироваться в строку

2022-02-12 17:31 UTC, Alexundar commented on src/services/csv/csv_service.py
> +    def convert_weather_to_csv_response(self, data_list: list) -> StreamingResponse:
шаблон будет выгляеть примрно так: `'%s;%s;%s;'`
вставка в шаблон примерно так:
```
for model in data_list:
    line = sample % (*model)
    stream.write(line)
```

2022-02-12 17:31 UTC, Alexundar commented on src/services/weather/weather_service.py
> +        if query.start_date:
можно вынести в отдельный метод

2022-02-12 17:31 UTC, Alexundar commented on src/weather_collector/main.py
> +    date_list = get_dates(start_date=date(2022, 1, 1), end_date=date(2022, 1, 15))
в `if __name__ == '__main__':` запускай только функцию main. плюс получение дат можно вынести в отдельный метод в date_utils

2022-02-12 17:31 UTC, Alexundar commented on src/weather_collector/scrapper/abstract_scrapper.py
> +    def scrap_weather(self, date_list: list):
назови метод просто scrap

2022-02-12 17:31 UTC, Alexundar commented on src/weather_collector/scrapper/abstract_scrapper.py
> +    def scrap_weather(self, date_list: list):
плюс в этом абстрактном методе передай в агрументы `(self, *args, **kwargs)`. а уже в методе scrap для WeatherScrapper пускай в аргументах будет date_list. это чтобы не завязывать нащ абстрактный метод на конкретную реализацию скрапера погоды

2022-02-12 17:31 UTC, Alexundar commented on src/weather_collector/scrapper/abstract_scrapper.py
> +    def scrap_weather(self, date_list: list):
так же надо сделать и с краулером

2022-02-14 08:30 UTC, Alexundar requested changes

2022-02-14 08:30 UTC, Alexundar commented on src/services/weather/weather_service.py
> +            print(day_time)
print

2022-02-14 08:30 UTC, Alexundar commented on src/utils/string_utils.py
> +def weather_model_to_csv_line(model: WeatherResponse):
`-> str`

2022-02-14 08:30 UTC, Alexundar commented on src/weather_collector/main.py
> +    weather = await weather_scrapper.scrap_content(date_list)
а где сохранение в бд?

2022-02-14 08:30 UTC, Alexundar commented on src/orm/schemas/responses/weather.py
> +    day_time: DayTimeResponse | str
я думаю можно просто str

2022-02-14 08:36 UTC, SayNya commented on src/orm/schemas/responses/weather.py
> +    day_time: DayTimeResponse | str
Нельзя

2022-02-17 07:13 UTC, Alexundar requested changes

2022-02-17 07:13 UTC, Alexundar commented on src/services/weather/weather_service.py
> +        translate_conditions = {
class Conditions(Enum):
     PARTLY_CLOUDY = 'малооблачно'
    ...

CONDITIONS_MAPPING = {
    Conditions.PARTLY_CLOUDY: 'partly_cloudy',
    ...

2022-02-17 07:13 UTC, Alexundar commented on src/services/weather/weather_service.py
> +        for model in pydantic_models:
вынести в отдельный метод def __destructure_conditions

2022-02-17 08:26 UTC, Alexundar approved these changes

2022-02-17 08:27 UTC, merged